"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bdyTL1w7KG1
 */
import Link from "next/link";
import { useState } from "react";

interface QABoxProps {
  question: string;
  answer: string[];
  correct: string;
}

export function QABox() {
  const [checked, setChecked] = useState<string>();
  return (
    <form>
      <div className="bg-white shadow overflow-hidden sm:rounded-lg dark:bg-gray-900">
        <div className="px-4 py-5 sm:px-6">
          <h3 className="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">
            Question 1
          </h3>
          <p className="mt-1 max-w-2xl text-sm text-gray-500 dark:text-gray-400">
            The question text goes here...
          </p>
        </div>
        <div className="border-t border-gray-200 dark:border-gray-700">
          <dl>
            <div className="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-gray-800">
              <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">
                <div className="flex flex-row justify-evenly">
                  <input
                    onChange={(e) => setChecked(e.target.value)}
                    className="h-5 w-5 text-zinc-600 border-gray-300 dark:border-gray-700 focus:ring-zinc-500"
                    name="question1"
                    type="radio"
                    value="A"
                  />
                </div>
              </dt>
              <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-gray-100">
                The option text goes here...
              </dd>
            </div>
            <div className="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-gray-900">
              <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">
                <div className="flex flex-row justify-evenly">
                  <input
                    onChange={(e) => setChecked(e.target.value)}
                    className="h-5 w-5 text-zinc-600 border-gray-300 dark:border-gray-700 focus:ring-zinc-500"
                    name="question1"
                    type="radio"
                    value="B"
                  />
                </div>
              </dt>
              <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-gray-100">
                The option text goes here...
              </dd>
            </div>

            <div className="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-gray-800">
              <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">
                <div className="flex flex-row justify-evenly">
                  {" "}
                  <input
                    onChange={(e) => setChecked(e.target.value)}
                    className="h-5 w-5 text-zinc-600 border-gray-300 dark:border-gray-700 focus:ring-zinc-500"
                    name="question1"
                    type="radio"
                    value="C"
                  />
                </div>
              </dt>
              <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-gray-100">
                The option text goes here...
              </dd>
            </div>

            <div className="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-gray-900">
              <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">
                <div className="flex flex-row justify-evenly">
                  {" "}
                  <input
                    onChange={(e) => setChecked(e.target.value)}
                    className="h-5 w-5 text-zinc-600 border-gray-300 dark:border-gray-700 focus:ring-zinc-500"
                    name="question1"
                    type="radio"
                    value="D"
                  />
                </div>
              </dt>
              <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-gray-100">
                The option text goes here...
              </dd>
            </div>
          </dl>
        </div>
      </div>
      <div className="flex flex-col gap-2 min-[400px]:flex-row mt-8">
        <button
          onClick={(e) => {
            e.preventDefault();
            console.log(e);
          }}
          className="inline-flex h-10 items-center justify-center rounded-md bg-zinc-900 px-8 text-sm font-medium text-zinc-50 shadow transition-colors hover:bg-zinc-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90 dark:focus-visible:ring-zinc-300"
          type="submit"
        >
          Check
        </button>
        <button className="inline-flex h-10 items-center justify-center rounded-md border border-zinc-200 border-zinc-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:border-zinc-800 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:bg-zinc-800 dark:hover:text-zinc-50 dark:focus-visible:ring-zinc-300">
          I don't remember.
        </button>
      </div>
    </form>
  );
}
