"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qd3DeF4pzwc
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { trace } from "console";
import Image from "next/image";
import { useRouter } from "next/navigation";

export function UploadBox() {
  const [file, setFile] = useState<File>();
  const [isUploading, setIsUploading] = useState(false);
  const router = useRouter();

  function uploadFile() {
    setTimeout(() => {}, 300);
    router.push("/view-paper");
  }

  const BoxContent = () => {
    if (file) {
      return (
        <div
          className="flex flex-row items-center justify-around"
          style={{ width: "100%" }}
        >
          <Image
            src={"/fileicon.png"}
            alt="File Icon"
            width={100}
            height={130}
          />
          <h1>{file.name}</h1>
        </div>
      );
    } else if (isUploading) {
      return (
        <Image
          src={"loading.svg"}
          alt="Loading Spinner"
          height={30}
          width={30}
        />
      );
    } else {
      return (
        <>
          <svg
            className=" w-12 h-12 text-gray-400 dark:text-gray-500"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="m5 12 7-7 7 7" />
            <path d="M12 19V5" />
          </svg>
          <Label
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mt-4"
            htmlFor="photo-upload"
          >
            Select a photo or drop it here
          </Label>
          <Input
            onChange={fileChange}
            className="mt-1 block w-full opacity-0 absolute inset-0 z-50"
            id="photo-upload"
            type="file"
            accept="image/jpg"
          />
        </>
      );
    }
  };

  function fileChange(event: React.ChangeEvent<HTMLInputElement>) {
    setIsUploading(true);
    const fileInput = event.target;

    if (!fileInput.files || !fileInput.files.length) {
      return;
    }

    setFile(fileInput.files[0]);
    setIsUploading(false);
  }
  return (
    <div className="flex flex-col items-center justify-center min-h-[100vh]">
      <div className="p-4 sm:p-6 lg:p-8 h-lg bg-white dark:bg-gray-800 rounded-lg shadow-md w-full max-w-lg mx-auto">
        <h2 className="text-2xl font-bold text-center text-gray-900 dark:text-gray-100">
          Upload Your Test Papers or Notes.
        </h2>
        <h4 className="text-xl text-center">
          We only accept .jpg files right now.
        </h4>
        <div className="mt-4 flex flex-col items-center justify-center border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg p-10">
          <BoxContent />
        </div>
        <Button
          className="w-full mt-6 py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
          variant="default"
          disabled={!file || isUploading}
          onClick={uploadFile}
        >
          Upload
        </Button>
      </div>
    </div>
  );
}
